apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: prod
images:
- name: cloud-native-app
  newName: NOOR/cloud-native-app # Zorg dat NOOR je Docker Hub naam is
  newTag: prod-latest